# Gray-Scott reaction-diffusion model

This notebook will run the Gray-Scott Reaction-Diffusion model to answer questions posed in the assignment and showcase model usage.

### 1. Imports

To run the code we import the neccesary class and functions

In [15]:
from gs_class import GrayScott
from gs_visual import create_animation, plot_field_UV, plot_field

### 2 Class Structure (explanation)
The Class imidiately initializes a Gray-Scott reaction diffusion grid for U and V with initial conditions as described below. The class implements Neumann Boundary conditions. Below are the initial conditions as described in the assignment:

In [16]:
n: int = 100,
center: int = 6,
i_value_U: float = 0.5,
i_value_V: float = 0.25,
dx: float = 1.0,
dt: float = 1.0,
dU: float = 0.16,
dV: float = 0.08,
feed: float = 0.035,
kill: float = 0.06, 
noise: float = 0.0

To create a class simply do the following:

In [17]:
# With initial conditions as described above
gray_scott = GrayScott()

# With some different initial conditions 
# These are not recommended for further usage
n = 5
center = 1
i_value_U = 0.6
i_value_V = 0.35

gray_scott2 = GrayScott(n, center, i_value_U, i_value_V)

The classes hold the grids for U and V as self.U and self.V as np.array.

In [18]:
print(gray_scott2.U)
print(gray_scott2.V)

[[0.6 0.6 0.6 0.6 0.6 0.6 0.6]
 [0.6 0.6 0.6 0.6 0.6 0.6 0.6]
 [0.6 0.6 0.6 0.6 0.6 0.6 0.6]
 [0.6 0.6 0.6 0.6 0.6 0.6 0.6]
 [0.6 0.6 0.6 0.6 0.6 0.6 0.6]
 [0.6 0.6 0.6 0.6 0.6 0.6 0.6]
 [0.6 0.6 0.6 0.6 0.6 0.6 0.6]]
[[0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.35 0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.   0.  ]]


The Class can be updated simply by calling on the update function. Which will automatically store the new grids for U and V in seld.U and self.V respecitively.

In [19]:
gray_scott.update()

### 3. Visualisation
The Gray Scott model can be visualised by plots of the field at a given iteration or an animation.